### ISSUE TITLE
could not load ddp model

### ISSUE THREAD

**Issue by happyday-lkj** [zhangcheng828/MonoDetector#3]
hello, I trained model in ddp model, but I could not load the model, 
error:
Unexpected key(s) in state_dict: "head.heatmap_head.1.weight_", "head.heatmap_head.1.bias_", "head.wh_head.1.weight_", "head.wh_head.1.bias_", "head.offset_head.1.weight_", "head.offset_head.1.bias_", "head.center2kpt_offset_head.1.weight_", "head.center2kpt_offset_head.1.bias_", "head.kpt_heatmap_head.1.weight_", "head.kpt_heatmap_head.1.bias_", "head.kpt_heatmap_offset_head.1.weight_", "head.kpt_heatmap_offset_head.1.bias_", "head.dim_head.1.weight_", "head.dim_head.1.bias_", "head.depth_head.1.weight_", "head.depth_head.1.bias_", "head.dir_feat.1.weight_", "head.dir_feat.1.bias_".

**Comment by happyday-lkj** [comment]
solved

**Comment by RookieHuang** [comment]
@happyday-lkj Could you share your solution?
